name: ubuntu_wsl_setup
description: Ubuntu WSL OOBE Setup Wizard
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ubuntu_wizard:
    path: ../ubuntu_wizard

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
  provider: ^5.0.0
  wizard_router: ^0.1.0+1

flutter:
  generate: true
  uses-material-design: true
